package com.alphadle.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF226A4C)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFAAF2CC)
private val onPrimaryContainerLight = Color(0xFF002114)
private val secondaryLight = Color(0xFF4D6357)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFD0E9D8)
private val onSecondaryContainerLight = Color(0xFF0A1F16)
private val tertiaryLight = Color(0xFF3D6473)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFC0E9FB)
private val onTertiaryContainerLight = Color(0xFF001F29)
private val errorLight = Color(0xFF904A43)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF3B0907)
private val backgroundLight = Color(0xFFF5FBF5)
private val onBackgroundLight = Color(0xFF171D19)
private val surfaceLight = Color(0xFFF5FBF5)
private val onSurfaceLight = Color(0xFF171D19)
private val surfaceVariantLight = Color(0xFFDCE5DD)
private val onSurfaceVariantLight = Color(0xFF404943)
private val outlineLight = Color(0xFF707973)
private val outlineVariantLight = Color(0xFFC0C9C1)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF2C322E)
private val inverseOnSurfaceLight = Color(0xFFEDF2EC)
private val inversePrimaryLight = Color(0xFF8ED5B1)
private val surfaceDimLight = Color(0xFFD6DBD6)
private val surfaceBrightLight = Color(0xFFF5FBF5)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF0F5EF)
private val surfaceContainerLight = Color(0xFFEAEFE9)
private val surfaceContainerHighLight = Color(0xFFE4EAE4)
private val surfaceContainerHighestLight = Color(0xFFDEE4DE)

private val primaryLightMediumContrast = Color(0xFF004D33)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF3B8162)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF32473C)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF637A6C)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF1F4856)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF537A8A)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF6E302A)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFAA6058)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFF5FBF5)
private val onBackgroundLightMediumContrast = Color(0xFF171D19)
private val surfaceLightMediumContrast = Color(0xFFF5FBF5)
private val onSurfaceLightMediumContrast = Color(0xFF171D19)
private val surfaceVariantLightMediumContrast = Color(0xFFDCE5DD)
private val onSurfaceVariantLightMediumContrast = Color(0xFF3C453F)
private val outlineLightMediumContrast = Color(0xFF58615B)
private val outlineVariantLightMediumContrast = Color(0xFF747D76)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF2C322E)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFEDF2EC)
private val inversePrimaryLightMediumContrast = Color(0xFF8ED5B1)
private val surfaceDimLightMediumContrast = Color(0xFFD6DBD6)
private val surfaceBrightLightMediumContrast = Color(0xFFF5FBF5)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF0F5EF)
private val surfaceContainerLightMediumContrast = Color(0xFFEAEFE9)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE4EAE4)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFDEE4DE)

private val primaryLightHighContrast = Color(0xFF002819)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF004D33)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF11261C)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF32473C)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF002631)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF1F4856)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF44100D)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF6E302A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFF5FBF5)
private val onBackgroundLightHighContrast = Color(0xFF171D19)
private val surfaceLightHighContrast = Color(0xFFF5FBF5)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFDCE5DD)
private val onSurfaceVariantLightHighContrast = Color(0xFF1D2621)
private val outlineLightHighContrast = Color(0xFF3C453F)
private val outlineVariantLightHighContrast = Color(0xFF3C453F)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF2C322E)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFB3FCD5)
private val surfaceDimLightHighContrast = Color(0xFFD6DBD6)
private val surfaceBrightLightHighContrast = Color(0xFFF5FBF5)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF0F5EF)
private val surfaceContainerLightHighContrast = Color(0xFFEAEFE9)
private val surfaceContainerHighLightHighContrast = Color(0xFFE4EAE4)
private val surfaceContainerHighestLightHighContrast = Color(0xFFDEE4DE)

private val primaryDark = Color(0xFF8ED5B1)
private val onPrimaryDark = Color(0xFF003824)
private val primaryContainerDark = Color(0xFF005236)
private val onPrimaryContainerDark = Color(0xFFAAF2CC)
private val secondaryDark = Color(0xFFB4CCBD)
private val onSecondaryDark = Color(0xFF20352A)
private val secondaryContainerDark = Color(0xFF364B40)
private val onSecondaryContainerDark = Color(0xFFD0E9D8)
private val tertiaryDark = Color(0xFFA5CDDE)
private val onTertiaryDark = Color(0xFF063543)
private val tertiaryContainerDark = Color(0xFF244C5A)
private val onTertiaryContainerDark = Color(0xFFC0E9FB)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF561E19)
private val errorContainerDark = Color(0xFF73332E)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF0F1511)
private val onBackgroundDark = Color(0xFFDEE4DE)
private val surfaceDark = Color(0xFF0F1511)
private val onSurfaceDark = Color(0xFFDEE4DE)
private val surfaceVariantDark = Color(0xFF404943)
private val onSurfaceVariantDark = Color(0xFFC0C9C1)
private val outlineDark = Color(0xFF8A938C)
private val outlineVariantDark = Color(0xFF404943)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFDEE4DE)
private val inverseOnSurfaceDark = Color(0xFF2C322E)
private val inversePrimaryDark = Color(0xFF226A4C)
private val surfaceDimDark = Color(0xFF0F1511)
private val surfaceBrightDark = Color(0xFF353B37)
private val surfaceContainerLowestDark = Color(0xFF0A0F0C)
private val surfaceContainerLowDark = Color(0xFF171D19)
private val surfaceContainerDark = Color(0xFF1B211D)
private val surfaceContainerHighDark = Color(0xFF262B28)
private val surfaceContainerHighestDark = Color(0xFF303632)

private val primaryDarkMediumContrast = Color(0xFF92DAB5)
private val onPrimaryDarkMediumContrast = Color(0xFF001B0F)
private val primaryContainerDarkMediumContrast = Color(0xFF599E7D)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFB8D1C1)
private val onSecondaryDarkMediumContrast = Color(0xFF051A11)
private val secondaryContainerDarkMediumContrast = Color(0xFF7F9688)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFA9D1E2)
private val onTertiaryDarkMediumContrast = Color(0xFF001922)
private val tertiaryContainerDarkMediumContrast = Color(0xFF6F96A7)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFBAB2)
private val onErrorDarkMediumContrast = Color(0xFF330404)
private val errorContainerDarkMediumContrast = Color(0xFFCC7B72)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF0F1511)
private val onBackgroundDarkMediumContrast = Color(0xFFDEE4DE)
private val surfaceDarkMediumContrast = Color(0xFF0F1511)
private val onSurfaceDarkMediumContrast = Color(0xFFF7FCF6)
private val surfaceVariantDarkMediumContrast = Color(0xFF404943)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFC4CDC5)
private val outlineDarkMediumContrast = Color(0xFF9CA59E)
private val outlineVariantDarkMediumContrast = Color(0xFF7C857F)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFDEE4DE)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF262B28)
private val inversePrimaryDarkMediumContrast = Color(0xFF005337)
private val surfaceDimDarkMediumContrast = Color(0xFF0F1511)
private val surfaceBrightDarkMediumContrast = Color(0xFF353B37)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0A0F0C)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF171D19)
private val surfaceContainerDarkMediumContrast = Color(0xFF1B211D)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF262B28)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF303632)

private val primaryDarkHighContrast = Color(0xFFEEFFF2)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFF92DAB5)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFEEFFF2)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFB8D1C1)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFF6FBFF)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFA9D1E2)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFBAB2)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF0F1511)
private val onBackgroundDarkHighContrast = Color(0xFFDEE4DE)
private val surfaceDarkHighContrast = Color(0xFF0F1511)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF404943)
private val onSurfaceVariantDarkHighContrast = Color(0xFFF4FDF5)
private val outlineDarkHighContrast = Color(0xFFC4CDC5)
private val outlineVariantDarkHighContrast = Color(0xFFC4CDC5)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFDEE4DE)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF00311F)
private val surfaceDimDarkHighContrast = Color(0xFF0F1511)
private val surfaceBrightDarkHighContrast = Color(0xFF353B37)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF0A0F0C)
private val surfaceContainerLowDarkHighContrast = Color(0xFF171D19)
private val surfaceContainerDarkHighContrast = Color(0xFF1B211D)
private val surfaceContainerHighDarkHighContrast = Color(0xFF262B28)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF303632)

internal val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

internal val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

internal val mediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

internal val highContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

internal val mediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

internal val highContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)